/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.panel;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LinearGradientPaint;
import java.awt.RenderingHints;
import java.awt.geom.Point2D;

/**
 *
 * @author The Anh
 */
public class WindowControlPanel extends javax.swing.JPanel {
     
    /**
     * Creates new form WindowControlPanel
     */
    
    public WindowControlPanel() {
        initComponents();
        
        // Thêm một nút để thay đổi màu mỗi lần nhấn
        
        
           
        
    
    }

  
//    protected void paintComponent(Graphics g) {
//        Graphics2D g2 = (Graphics2D) g;
//        Point2D start = new Point2D.Float(0, 0);
//        Point2D end = new Point2D.Float(getWidth(), getHeight());
//        float[] fractions = {0.0f, 0.5f, 1.0f};
//        Color[] colors = {
//            Color.decode("#0f0c29"),
//            Color.decode("#302b63"),
//            Color.decode("#24243e")
//        };
//        GradientPaint gpBorder = new GradientPaint(
//            0, 0, Color.decode("#A1FFCE"),           // Điểm bắt đầu + màu
//            getWidth(), getHeight(), Color.decode("#FAFFD1") // Điểm kết thúc + màu
//        );
//        LinearGradientPaint paint = new LinearGradientPaint(start,end, fractions, colors);
//        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        g2.setPaint(paint);
//        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
//        g2.setPaint(gpBorder);
//        g2.setStroke(new BasicStroke(3));
//        g2.drawRoundRect(0,0,getWidth()-1,getHeight()-1,30,30);
//        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        super.paintComponent(g);
//        
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borderPanel1 = new raven.panel.BorderPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");

        javax.swing.GroupLayout borderPanel1Layout = new javax.swing.GroupLayout(borderPanel1);
        borderPanel1.setLayout(borderPanel1Layout);
        borderPanel1Layout.setHorizontalGroup(
            borderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        borderPanel1Layout.setVerticalGroup(
            borderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borderPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borderPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.panel.BorderPanel borderPanel1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
